"""`sommus stats`: turn the SQLite log and eval results into docs/MEASUREMENTS.md.

Everything here is aggregated — no request text leaves the machine — so the page can live in the
public repo. Charts are Mermaid, which GitHub renders, so there's no plotting dependency.
"""

from __future__ import annotations

import json
import sqlite3
from datetime import datetime
from pathlib import Path

from sommus.brain.budget import NO_EFFORT

MODEL_LABEL = {"claude-opus-5": "Opus 5", "claude-sonnet-5": "Sonnet 5", "claude-haiku-4-5": "Haiku 4.5"}


def daily(db: sqlite3.Connection) -> list[tuple]:
    return db.execute(
        """
        SELECT substr(started_at, 1, 10) AS day,
               COUNT(*),
               SUM(model = 'fastpath'),
               COALESCE(SUM(cost_usd), 0),
               AVG(CASE WHEN model NOT IN ('fastpath', 'pin') THEN cost_usd END),
               1.0 * SUM(cache_read_tokens) / NULLIF(SUM(cache_read_tokens + cache_write_tokens + input_tokens), 0)
        FROM turns GROUP BY day ORDER BY day
        """
    ).fetchall()


def totals(db: sqlite3.Connection) -> dict:
    count, fast, spent, reads, all_prompt = db.execute(
        """
        SELECT COUNT(*), SUM(model = 'fastpath'), COALESCE(SUM(cost_usd), 0), SUM(cache_read_tokens),
               SUM(cache_read_tokens + cache_write_tokens + input_tokens)
        FROM turns
        """
    ).fetchone()
    tools = db.execute("SELECT COUNT(*), SUM(is_error) FROM tool_calls").fetchone()
    return {
        "commands": count or 0,
        "fast": fast or 0,
        "spent": spent,
        "cache": (reads or 0) / all_prompt if all_prompt else 0.0,
        "tool_calls": tools[0] or 0,
        "tool_errors": tools[1] or 0,
    }


def evals(folder: Path, smallest: int = 20) -> list[dict]:
    """Full eval runs (not single `--only` checks), oldest first."""
    runs = []
    for path in sorted(folder.glob("*.json")):
        run = json.loads(path.read_text())
        if run.get("total", 0) >= smallest:
            cases = run.get("cases", [])
            seconds = [c.get("seconds", 0) for c in cases if isinstance(c, dict)]
            runs.append(
                {
                    "when": run["ran_at"][:16].replace("T", " "),
                    "model": MODEL_LABEL.get(run["model"], run["model"]),
                    "effort": "—" if run["model"] in NO_EFFORT else run.get("effort", ""),
                    "passed": run["passed"],
                    "total": run["total"],
                    "per_command": run["cost_usd"] / run["total"],
                    "seconds": sum(seconds) / len(seconds) if seconds else None,
                }
            )
    return runs


def _bar(title: str, labels: list[str], values: list[float], axis: str) -> str:
    top = max(values) * 1.2 if values and max(values) > 0 else 1
    return (
        "```mermaid\nxychart-beta\n"
        f'    title "{title}"\n'
        f"    x-axis [{', '.join(repr(label).replace(chr(39), chr(34)) for label in labels)}]\n"
        f'    y-axis "{axis}" 0 --> {top:.3g}\n'
        f"    bar [{', '.join(f'{v:.3g}' for v in values)}]\n```"
    )


def render(db_path: Path, evals_dir: Path) -> str:
    db = sqlite3.connect(db_path)
    t = totals(db)
    days = daily(db)
    runs = evals(evals_dir)
    lines = [
        "# Measurements",
        "",
        f"Generated by `sommus stats` on {datetime.now():%Y-%m-%d} from Sommus's own SQLite log and eval results.",
        "Aggregates only — no request text. Includes eval runs, which are most of the early traffic.",
        "",
        "## Headline",
        "",
        "| | |",
        "|---|---|",
        f"| Commands handled | {t['commands']:,} |",
        f"| Answered with no model call (fast path) | {t['fast']:,} |",
        f"| Total API spend | ${t['spent']:.2f} |",
        f"| Prompt tokens served from cache (0.1× price) | {t['cache']:.0%} |",
        f"| Tool calls · errors | {t['tool_calls']:,} · {t['tool_errors']} ({t['tool_errors'] / t['tool_calls']:.0%}) |"
        if t["tool_calls"]
        else "| Tool calls | 0 |",
        "",
        "## Cost per model-handled command, by day",
        "",
        _bar(
            "Average cost per command that reached the model (cents)",
            [d[0][5:] for d in days],
            [(d[4] or 0) * 100 for d in days],
            "cents",
        ),
        "",
        "| Day | Commands | Fast path | Spend | Avg per model command | Cache share |",
        "|---|---|---|---|---|---|",
    ]
    for day, count, fast, spent, avg, cache in days:
        avg_text = f"{avg * 100:.2f}¢" if avg is not None else "—"
        cache_text = f"{cache:.0%}" if cache is not None else "—"
        lines.append(f"| {day} | {count} | {fast or 0} | ${spent:.2f} | {avg_text} | {cache_text} |")
    if runs:
        lines += [
            "",
            "## Eval runs (tool-call accuracy vs cost)",
            "",
            "Each run replays `evals/commands.toml` in fresh conversations; read-only tools run for real,",
            "the rest are simulated. The suite grew from 20 to 46 commands as tools were added.",
            "",
            "| When | Model | Effort | Score | Per command | Avg latency |",
            "|---|---|---|---|---|---|",
        ]
        for r in runs:
            latency = f"{r['seconds']:.1f} s" if r["seconds"] else "—"
            lines.append(
                f"| {r['when']} | {r['model']} | {r['effort']} | {r['passed']}/{r['total']} | "
                f"{r['per_command'] * 100:.2f}¢ | {latency} |"
            )
    lines += ["", "Design decisions behind these numbers: [docs/decisions](decisions/).", ""]
    return "\n".join(lines)


def write(db_path: Path, evals_dir: Path, out: Path) -> Path:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(db_path, evals_dir))
    return out
